#!/bin/bash


# Python
alias python='/usr/local/bin/python3'
alias pip='pip3'

# Alias repos and folders
alias viz='cd ~/Desktop/recidiviz/'
alias rdata='cd ~/Desktop/recidiviz/recidiviz-data'
alias esh='cd ~/Desktop/ESH/'
alias desktop='cd ~/Desktop/'
alias dotfiles='code ~/.dotfiles/'
alias reflect='touch ~/.reflections/$( date "+%Y_%m_%d_%H_%M_%S" ).md && cd ~/.reflections'
alias apis='cd ~/apis-052019'

# Git
alias gs='git status'
alias gpull='git pull origin'
alias gpush='git push origin'
alias git=hub
alias gcl='git clone'

# docker
alias dc='docker-compose'
alias dcx='docker-compose exec web bundle exec'

# bash
alias copy=pbcopy
alias paste=pbpaste
alias ls='ls -aGF'
alias l='ls -tBh1'
alias ll='l -l'
alias lll='ls -Blah'
alias llh='ll | head'
alias grep='grep --color'
alias g='grep -i'
alias df='df -h'
alias du='du -h'
alias less='less -r'
alias fu='kill -9 %1; ps'
alias reveal='open -R'
alias vi="vim"
alias o='open'
alias e="${EDITOR}"

# ruby / rails
alias be='bundle exec'
alias bake='bundle exec rake db:create db:migrate'
alias clobpile='bundle exec rake assets:clobber assets:precompile'
alias rspec='bundle exec rspec'
