#!/bin/bash

DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for FILE in bash_profile bashrc irbrc rails.irbrc gitconfig pryrc inputrc gemrc; do
  LINK="$HOME/.$(basename $FILE)"
  if [[ -L "$LINK" ]] && [[ $(readlink "$LINK") = "$DOTFILES/$FILE" ]]; then
    echo "$LINK -> $DOTFILES/$FILE"
    continue
  fi
  if [[ -e "$LINK" ]]; then
  	/bin/echo -n "overwrite $LINK? "
  	read
  	[[ "$REPLY" != "y" ]] && continue
  fi
  ln -fs "$DOTFILES/$FILE" "$LINK"
  echo "$LINK -> $DOTFILES/$FILE"
done
